%YAML:1.0
imu0:
  T_i_b:
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]

  accelerometer_noise_density: 3.76863e-02
  accelerometer_random_walk: 1.14166e-03
  gyroscope_noise_density: 2.34175e-03
  gyroscope_random_walk: 1.44284e-05
  model: calibrated
  rostopic: /handsfree/imu
  time_offset: 0.0
  update_rate: 150.0
  Tw:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1]

  R_IMUtoGYRO:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1]

  Ta:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1]

  R_IMUtoACC:
    - [1, 0, 0]
    - [0, 1, 0]
    - [0, 0, 1]

  Tg:
    - [0, 0, 0]
    - [0, 0, 0]
    - [0, 0, 0]

